### ISSUE TITLE
Instalar e conectar o BD

### ISSUE THREAD

**Issue by swfsql** [swfsql/itabirapp#2]
To tentando instalar o mysql (workbench + o mysql msm)
https://dev.mysql.com/downloads/workbench/
https://dev.mysql.com/downloads/windows/

com o workbench da pra criar um "modelo" e criar certinho o nome do "esquema" (itabirapp_db), um usuário com nome (itabirapp_user), senha (itabirapp_senha) e acesso (owner, etc) certinhos.
![workbench](https://cloud.githubusercontent.com/assets/1165577/19212924/47699d4e-8d34-11e6-9823-2438a70106a0.PNG)

Depois disso precisa criar o BD mesmo e então testar a conexão do beego com o BD.. acho que criar um "modelo" não cria o BD de verdade.

**Comment by swfsql** [comment]
a configuração deve ser dada noutro lugar msm, quando criar uma nova conexão com bd, daí cria um novo schema e tals..

img do usuário:
![workbench](https://cloud.githubusercontent.com/assets/1165577/19213701/4e7eec46-8d49-11e6-9b0a-bd43cc6b5e69.PNG)

**Comment by fecetrulo** [comment]
Please Try the following steps: 1) c:\mysql\bin>mysqld --install 2) c:\mysql\bin>mysqld --initialize

then press "Windows key + R" write "services.msc, run as admin start MySQL service.
