### ISSUE TITLE
colocar o campo da descrição pros posts

### ISSUE THREAD

**Issue by fecetrulo** [swfsql/itabirapp#29]
- [x] new
- [ ] edit
- [ ] view (parar de usar o Lorem e usar a descrição de verdade)

**Comment by 1234yang** [comment]
MVP is the implementation of the key features that communicate the idea of your product
What startups gain with MVP:
Save funds from waste
Opens communication with target audience
Brings light on strengths and weaknesses of the product
Thunderrise helps start ups on the early stages to enter the market.
thunderrise.com

**Comment by 1234yang** [comment]
<a href="http://thunderrise.com/">Best app developer</a>
